services:
  redis:
    image: redis
  local-vercel-kv:
    image: hiett/serverless-redis-http:latest
    ports:
      - 8080:80
    environment:
      SRH_MODE: env
      SRH_TOKEN: local_token
      SRH_CONNECTION_STRING: redis://redis:6379
